# Generated by Django 5.0.2 on 2026-08-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_favorited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(max_length=255, upload_to='uploads/properties'),
        ),
    ]
